version: "3.7"

services:
  mondndiary:
    restart: always
    build: .
    ports: 
    - "4000:4000"
    - "35729:35729"
    volumes:
    - type: bind
      source: ./_posts
      target: /usr/src/app/_posts
    - type: bind
      source: ./_layouts
      target: /usr/src/app/_layouts
    - type: bind
      source: ./_sass
      target: /usr/src/app/_sass
    - type: bind
      source: ./_includes
      target: /usr/src/app/_includes
    - type: bind
      source: ./index.html
      target: /usr/src/app/index.html
    command: ["--host=0.0.0.0", " --force_polling", "--livereload"]
