version: "3.7"

services:
  mondndiary:
    image: ruby:2.7.3
    restart: always
    working_dir: /usr/src/app/
    ports:
    - "4000:4000"
    - "35729:35729"
    volumes:
    - type: bind
      source: ./
      target: /usr/src/app/
    command: ["bash", "-c", "bundle update && bundle exec jekyll server --host=0.0.0.0 --livereload"]
