name: discord message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        username: "MonD&Diary"
        avatar_url: "https://i.imgur.com/zo97OH9.jpeg"
        args: "> **${{ github.event.pusher.name }}** pushed `${{ github.event.head_commit.message }}` into the repo, it'll be up any minute now: https://malde.me/mondndiary"
